#!/bin/sh


echo "Compiling"
mvn compile
if [ $? -ne 0 ]; then
  echo "Compilation failed"
  exit 1
fi

echo "Checkstyle"
mvn checkstyle:check
if [ $? -ne 0 ]; then
  echo "Checkstyle violations found"
  exit 1
fi

echo "Formatting with Spotless."
mvn formatter:format
git add -u



echo "SpotBugs analysis..."
mvn spotbugs:spotbugs -X



echo 
exit 0